In [3]:
import tensorflow.compat.v1 as tf # 1.XX version 을 사용 
tf.disable_v2_behavior() # 2.xx version 기능을 사용하지 않겠음
import numpy as np
import pandas as pd

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
# 포유류? 조류? 기타? 분류기 (신경망)
# 기준 - 털, 날개유무에 따라 분류
# [털,날개]
xdata = np.array(
    [[0,0],
    [1,0],
    [1,1],
    [0,0],
    [0,0],
    [0,1]
    ]
)
ydata = np.array(
    [[1,0,0], #기타
    [0,1,0], #포유류
    [0,0,1], #조류
    [1,0,0],
    [1,0,0],
    [0,0,1]
    ]
)

In [9]:
#신경망 모델 구성
x = tf.placeholder(tf.float32, [None, 2])
y = tf.placeholder(tf.float32, [None, 3]) #뷴류기가 3개니까 3이에요! 한개만 1, 나머지는 0
w = tf.Variable(tf.random_uniform([2,3], -1, 1))
# hf = x*w + b
# none ,2 * 2,3 => none, 3
b = tf.Variable(tf.zeros([3]))

In [15]:
L = tf.add(tf.matmul(x, w), b) # [none, 3] 와 [3] 요소간 덧셈

# sigmoid(L)
L = tf.nn.relu(L) # relu 함수는 음수가 전달되는 경우에는 0, 양수가 전달되는 경우에는 양수 값을 그대로 리턴해주는 함수


In [16]:
model = tf.nn.softmax(L) # 신경말 모델
cost = tf.reduce_mean(-tf.reduce_sum(y*tf.log(model), axis = 1))
train = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

In [17]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [18]:
for step in range(101):
    sess.run(train, feed_dict = {x:xdata, y:ydata})
print(sess.run(model, feed_dict={x:xdata}))

[[0.33333334 0.33333334 0.33333334]
 [0.4684087  0.2953446  0.23624673]
 [0.27568555 0.5106305  0.21368392]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.26181594 0.4763681  0.26181594]]


In [ ]:
prediction = tf.argmax(model, axis = 1)
target = tf.argmax(y,1)



In [19]:
L1=tf.add(tf.matmul(x,w1), b1)
L1=tf.nn.relu(L1) 
model=tf.add(tf.matmul(L1, w2), b2)
cost=tf.reduce_mean(
    tf.reduce_sum(tf.nn.softmax_cross_entropy_with_logits_v2(labels=y, logits=model)))
train=tf.train.AdamOptimizer(0.01).minimize(cost)

NameError: name 'w1' is not defined