In [230]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

# 자연어 처리를 위한 라이브러리 설치

1) 텐서플로우  
2) 케라스  
3) 젠심(gensim)  
4) 사이킷런  
5) nltk(영문관련한 자연어처리)  
6) kolnpy  
7) jpype   

In [231]:
from nltk.tokenize import word_tokenize

In [232]:
print(word_tokenize("""Don't be fooled by the dark sounding name, Mr.jone's Orphanage is as cheery as cheery goes for a pastery shop"""))

['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastery', 'shop']


In [233]:
from nltk.tokenize import wordpunct_tokenize

print(wordpunct_tokenize("""Don't be fooled by the dark sounding name, Mr.jone's Orphanage is as cheery as cheery goes for a pastery shop"""))

['Don', "'", 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr', '.', 'jone', "'", 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastery', 'shop']


In [234]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence

print(text_to_word_sequence(""""Don't be fooled by the dark sounding name, Mr.jone's Orphanage is as cheery as cheery goes for a pastery shop"""))


["don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', 'mr', "jone's", 'orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastery', 'shop']


# 문장 토큰화

In [235]:
text1 = "I am actively looking for Ph.D. students. and you are a Ph.D student."
text2 = "His barber kept his word. But keeping such a huge secret to himself was driving him crazy. Finally, the barber went up a mountain and almost to the edge of a cliff. He dug a hole in the midst of some reeds. He looked about, to mae sure no one was near."

In [236]:
from nltk.tokenize import sent_tokenize
sent_tokenize(text1)
sent_tokenize(text2)

['His barber kept his word.',
 'But keeping such a huge secret to himself was driving him crazy.',
 'Finally, the barber went up a mountain and almost to the edge of a cliff.',
 'He dug a hole in the midst of some reeds.',
 'He looked about, to mae sure no one was near.']

# token
토큰이란? 분석을 하기 위한 수준으로 나누어주는 단위  
문자, 문장, 등 단위는 사용자가 원하는 수준으로 나눠짐

In [237]:
from nltk.tokenize import word_tokenize
print(word_tokenize(text1))

['I', 'am', 'actively', 'looking', 'for', 'Ph.D.', 'students', '.', 'and', 'you', 'are', 'a', 'Ph.D', 'student', '.']


In [238]:
from nltk.tag import pos_tag
imsi = word_tokenize(text1)
pos_tag(imsi) # 품사 단위로 출력이 됨

[('I', 'PRP'),
 ('am', 'VBP'),
 ('actively', 'RB'),
 ('looking', 'VBG'),
 ('for', 'IN'),
 ('Ph.D.', 'NNP'),
 ('students', 'NNS'),
 ('.', '.'),
 ('and', 'CC'),
 ('you', 'PRP'),
 ('are', 'VBP'),
 ('a', 'DT'),
 ('Ph.D', 'NNP'),
 ('student', 'NN'),
 ('.', '.')]

# 형태소 출력

In [239]:
from konlpy.tag import Okt #형태소를 출력
okt = Okt()
okt.morphs("열심히 공부한 우리. 취업에 성공합시다") # 형태소
okt.pos("열심히 공부한 우리. 취업에 성공합시다") 
okt.nouns("열심히 공부한 우리. 취업에 성공합시다") # 명사


['공부', '우리', '취업']

# 형태소 어간 추출  
어간(stem, 의미), 접사(부가적인 의미)   
dogs => dog(어간), -s(접사), cat(어간)   

In [240]:
from nltk.stem import WordNetLemmatizer
wn = WordNetLemmatizer()
words = ['loves', 'dies', 'complete', 'having']
print(wn.lemmatize(words[3]))

having


In [241]:
from nltk.stem import PorterStemmer
ps = PorterStemmer() # 어간 추출(품사 정보가 상실)
ps.stem(words[3])

'have'

In [242]:
from nltk.corpus import stopwords

In [243]:
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

# ex에 저장된 단어에서 불용어를 제거하고 출력

In [244]:
ex = 'Family is not an important thing. It;s everything.'

In [245]:
stop_words = set(stopwords.words('english'))

word_token = word_tokenize(ex)

result = []
for w in word_token:
    if w not in stop_words:
        result.append(w)

print(word_token)
print(result)

['Family', 'is', 'not', 'an', 'important', 'thing', '.', 'It', ';', 's', 'everything', '.']
['Family', 'important', 'thing', '.', 'It', ';', 'everything', '.']


In [246]:
from nltk.tokenize import RegexpTokenizer

tok = RegexpTokenizer("[\w]+") # 정규표현식 사용 
# \w = [a-zA-z]]
print(tok.tokenize('Family is not an important thing. It;s everything.'))

['Family', 'is', 'not', 'an', 'important', 'thing', 'It', 's', 'everything']


In [247]:
text = "A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."


# 문장 단위 토큰화

In [248]:
text = sent_tokenize(text)
print(text)

['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']


In [249]:
print(len(text))

11


# 11개의 문장 각각에 대해, 단어 토큰화 수행
1) 불용어는 제거  
2) 단어 길이가 2이하면 제거  
3) 모든 단어는 소문자화  

In [250]:
stop_words = set(stopwords.words('english'))
res = []

for i in range(0, len(text)):
    word_token = word_tokenize(text[i])
    result = []
    for w in word_token:
        if w not in stop_words and len(w) > 2:
            w = w.lower()
            result.append(w)
    res.append(result)
# print(word_token)
print(res)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['the', 'secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['his', 'barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['his', 'barber', 'kept', 'secret'], ['but', 'keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [251]:
vocab = {} 
sentences = []
stop_words = set(stopwords.words('english'))
for i in text:
    sentence = word_tokenize(i) 
    result = []
    for word in sentence: 
        word = word.lower() 
        if word not in stop_words:
            if len(word) > 2:
                result.append(word)
                if word not in vocab:
                    vocab[word] = 0 
                vocab[word] += 1
    sentences.append(result) 
print(sentences)


[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


# 빈도수를 기준으로 내림차순 출력(sorted 함수))
# 츨력예시



In [252]:
vs = sorted(vocab.items(), key=lambda x : x[1], reverse=True)

In [253]:
wti = {}
i = 0
for (word,f) in vs:
    if f>1 :
        i += 1
        wti[word] = i
print(wti)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7}


In [254]:
token = okt.morphs('오전에는 졸았지만, 오후에는 열심히 하겠다.')

# 토큰 단위로 딕셔너리에 저장하기 

In [255]:
word2index = {}

for v in token:
    if v not in word2index.keys(): # v 토큰이 word2 index에 없다면?
        word2index[v] = len(word2index)
print(word2index)



{'오전': 0, '에는': 1, '졸았지만': 2, ',': 3, '오후': 4, '열심히': 5, '하겠다': 6, '.': 7}


# 케라스 토크나이져

In [256]:
def ohe(w, word2index):
    ohv = [0]*len(word2index)
    idx = word2index[w]
    ohv[idx] = 1
    return ohv
print(ohe('오후', word2index))

[0, 0, 0, 0, 1, 0, 0, 0]


In [257]:
# text = '문일주 공부 좀 해, 너 요즘 놀고 있잖아'
from keras_preprocessing.text import Tokenizer
from keras.utils import to_categorical
text = """나랑 막걸리 마시러 갈래 안주는 파전 갈래 갈래 파전 최고야""" # 이게 코퍼스임!
t = Tokenizer()
t.fit_on_texts([text])


In [258]:
t.word_index # 형태소 분석을 해서 인덱스 먹임
t.index_word
enc = t.texts_to_sequences(['술 마시러 갈래 갈꺼야 말꺼야 갈래'])[0]
# 코퍼스로부터, 만들어 낸거 
enc # 2차원
to_categorical(enc) #차원이 하나가 늘어나서 저장


array([[0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.]], dtype=float32)

# bag of words
단어들이 들어가 있는 가방  
각 단어에 인덱스 부여 -> 등장 횟수 저장


# 마침표 제거하기

In [259]:
import re
# re.sub(패턴, 교체문자, 데이터)

token = re.sub("[.]+",'',"정부가 발표하는 물가상승률과 소비자가 느끼는 물가상승률은 다르다.")
token = re.sub("(\.)+",'',"정부가 발표하는 물가상승률과 소비자가 느끼는 물가상승률은 다르다.")


In [260]:
token

'정부가 발표하는 물가상승률과 소비자가 느끼는 물가상승률은 다르다'

In [261]:
token = okt.morphs(token)

In [272]:
bow = []
word2index = {}

for v in token:
    if v not in word2index.keys():
        # print(v)
        word2index[v] = len(word2index)  #{'정부' : 0, '가':1}
        bow.insert(len(word2index)-1, 1) # 0으로 각 자리를 초기화
    else: 
        idx = word2index.get(v)
        bow[idx] = bow[idx]+1
print(word2index)
print('='*20)
print(bow)



{'정부': 0, '가': 1, '발표': 2, '하는': 3, '물가상승률': 4, '과': 5, '소비자': 6, '느끼는': 7, '은': 8, '다르다': 9}
[1, 2, 1, 1, 2, 1, 1, 1, 1, 1]


insert 함수를 이용해서 원하는 위치에 추가할 수 있음

In [275]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = ['you know I want your love. because I love you']

vec = CountVectorizer()
# 각 단어의 빈도수
print(vec.fit_transform(corpus).toarray())
# 각 단어의 인덱스
print(vec.vocabulary_) # 인덱스는 알파벳 순으로 매김



[[1 1 2 1 2 1]]
{'you': 4, 'know': 1, 'want': 3, 'your': 5, 'love': 2, 'because': 0}


In [277]:
corpus = ['you know I want your love. because I love you']

vec = CountVectorizer(stop_words=['love'])  # 사용자가 직접 불용어를 지정할 경우 
# 각 단어의 빈도수
print(vec.fit_transform(corpus).toarray())
# 각 단어의 인덱스
print(vec.vocabulary_) # 인덱스는 알파벳 순으로 매김



[[1 1 1 2 1]]
{'you': 3, 'know': 1, 'want': 2, 'your': 4, 'because': 0}


In [279]:
from math import log


In [281]:
docs = ['먹고 싶은 사과', '먹고 싶은 바나나', '길고 노란 바나나 바나나', '저는 과일이 좋아요']

voc = list(set(w for doc in docs for w in doc.split()))
# <------------->
# 먹고싶은 사과 
#                 <------------------>
#                    먹고/ 싶은/ 사과

In [284]:
voc.sort()

In [285]:
n = len(docs)
def tfv(t, d):
    return d.count(t) # d문서에서 t 단어의 등장횟수
def idf(t):
    df = 0
    for doc in docs:
        df += t in doc
    return log(n/(df+1))

def tfidf(t,d):
    return tfv(t,d)*idf(t)
    

In [286]:
import pandas as pd

In [289]:
res = []
for i in range(n):
    res.append([])
    d =docs[i]
    for j in range(len(voc)):
        t= voc[j]
        res[-1].append(tfv(t,d))
mytf = pd.DataFrame(res, columns = voc)
mytf

과일이  길고  노란  먹고  바나나  사과  싶은  저는  좋아요
0    0   0   0   1    0   1   1   0    0
1    0   0   0   1    1   0   1   0    0
2    0   1   1   0    2   0   0   0    0
3    1   0   0   0    0   0   0   1    1

In [ ]:
res = []
for j in range(len(voc)):
    t= voc[j]
    res[-1].append(idf(t))
mytf = pd.DataFrame(res, columns = voc)
mytf

In [296]:
res = []
for i in range(n):
    res.append([])
    d = docs[i]
    for j in range(len(voc)):
        t = voc[j]
        res[-1].append(tfidf(t, d))
mytfidf = pd.DataFrame(res, columns = voc)
mytfidf

과일이        길고        노란  ...        싶은        저는       좋아요
0  0.000000  0.000000  0.000000  ...  0.287682  0.000000  0.000000
1  0.000000  0.000000  0.000000  ...  0.287682  0.000000  0.000000
2  0.000000  0.693147  0.693147  ...  0.000000  0.000000  0.000000
3  0.693147  0.000000  0.000000  ...  0.000000  0.693147  0.693147

[4 rows x 9 columns]

In [299]:
corpus= ['you know I want you love', 'I like you', ' what should I do']

# DTM 
vector = CountVectorizer()
print(vector.fit_transform(corpus).toarray())
print(vector.vocabulary_)

[[0 1 0 1 0 1 0 2]
 [0 0 1 0 0 0 0 1]
 [1 0 0 0 1 0 1 0]]
{'you': 7, 'know': 1, 'want': 5, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [300]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfv = TfidfVectorizer().fit(corpus)
print(tfidfv.transform(corpus).toarray())

[[0.         0.43381609 0.         0.43381609 0.         0.43381609
  0.         0.65985664]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.        ]]
